typedoc2md/typedoc-plugin-markdown

src/theme/helpers/getMarkdownFromHtml.ts
This won't currently have any effect, but it will once this PR over at `turndown` is merged, so it's definitely worth prepping for:
https://github.com/domchristie/turndown/pull/226
Once that PR is merged, I've confirmed locally that `typedoc-plugin-markdown` will correctly label fenced code examples that were generated from TypeDoc.
So if you have a TS file such as:
```typescript
/**
* Get file type settings
*
* ```typescript
* const fileSettings = await getFileTypeSettings('path/to/some/file.md')
* ```
*
* @public
* @param filename - The file to get settings for.
*/
export const getFileTypeSettings = async (filename: Filename) => {/**/}
```
TypeDoc will output the HTML as such:
```html
<pre><code class="lang-typescript"><span class="hljs-keyword">const</span> fileSettings = <span …
```
=> Make turndown default to using fenced code blocks

package-lock.json, package.json, src/theme/helpers/getMarkdownFromHtml.ts, test/fixtures/bitbucket/README.md, test/fixtures/bitbucket/classes/defaultexportedclass.md, test/fixtures/bitbucket/classes/notexportedclassname.md, test/fixtures/gitbook/classes/_default_export_.defaultexportedclass.md, test/fixtures/gitbook/classes/_default_export_.notexportedclassname.md, test/fixtures/gitbook/modules/_doc_comments_.md, test/fixtures/github/classes/_default_export_.defaultexportedclass.md, test/fixtures/github/classes/_default_export_.notexportedclassname.md, test/fixtures/github/modules/_doc_comments_.md, test/src/default-export.ts, test/src/doc-comments.ts
So sorry I was actually incorrect with my pull request earlier. Sincere apologies, especially since you already cut a release.
I'm sorry I missed it. I based my previous PR off a local change I made to turndown, but I didn't notice in my turndown tests I was calling turndown as a function with two parameters and that worked for me...but I didn't catch that you're actually using it as constructor, where the options actually need to be supplied to the constructor.
I promise it's correct this time!
=> Correct turndown configuration

src/theme/helpers/getMemberSymbol.ts, test/fixtures/bitbucket/modules/interfaces.md, test/fixtures/gitbook/modules/_interfaces_.interfaces.md, test/fixtures/github/modules/_interfaces_.interfaces.md
The current prefix is a capital "T" with no trailing space. This results in confusing definitions making it look like the actual type alias starts with "T". To address this, I made the following changes:
* Added a space after type alias prefix.
* Changed type alias prefix to a not english [UTF8 character resembling "T"](https://www.fileformat.info/info/unicode/char/01ac/browsertest.htm).
=> Change type alias prefix symbol and formatting to avoid confusion.

src/theme/utils.ts
Currently if there are two identifiers that differ just in case then links are broken. i.e, you have two functions or methods, etc named: "Call" and "call". Then references to the later will be broken because of the toLowerCase()
=> links to identifiers differing only in case

src/theme/partials/member.getterSetter.hbs, src/theme/partials/type.hbs, test/fixtures/bitbucket/classes/subclassa.md, test/fixtures/gitbook/classes/_classes_.subclassa.md, test/fixtures/github/classes/_classes_.subclassa.md
Type aliases may be escaped unexpectedly.
For example
```md
**Ƭ TC**: *`() &#x3D;&gt; void`*
```
which should be
```md
**Ƭ TC**: *`() => void`*
```
```
src/theme/partials/parameter.hbs:36:`{{this}}`
src/theme/partials/member.signature.title.hbs:7:`{{name}}`
src/theme/partials/member.parameters.hbs:8:`{{this}}`
src/theme/partials/member.parameters.hbs:15:`{{this}}`
src/theme/partials/member.parameters.hbs:26:`{{this}}`
```
There are some `{{  }}` tags in other files, but seem to not make mistake.
=> Disable HTML escaping in inline code blocks

src/lib/theme/partials/member.sources.hbs
This fixes an issue in a template file markdown that would cause "Defined in ..." hyperlinks to point to a nonexisting page.
=> Fixed theme template

README.md, src/lib/plugin.ts, src/lib/theme/helpers/breadcrumbs.ts, src/lib/theme/helpers/metadata.ts, src/lib/theme/helpers/project-title.ts, src/lib/theme/helpers/reflection-index.ts, src/lib/theme/templates/reflection.hbs, src/lib/theme/theme.vuepress.ts
This pull request adds VuePress support.
It could be better to not include `index` part to the created markdowns, because sidebar already has it. How can I disable that part in generated markdown files?
=> VuePress support

src/lib/theme/helpers/metadata.ts
This PR replaces `@someuser/` from `@someuser/module-name` when used in title meta data.
Additionally, backwards compatible, if `label` field is available in `package.json`, prefers to use that, otherwise uses project name.
**package.json**
```
{
name: @someuser/module-name
}
```
produces
```md
---
title: Fortibase Scrap
---
```
```
{
name: @someuser/awesome-module
label: AweSOME
}
```
produces
```md
---
title: AweSOME
---
```
=> replace @user from title, prefer label. Fixes #64

src/lib/theme/helpers/__snapshots__/metadata.spec.ts.snap, src/lib/theme/helpers/metadata.spec.ts, src/lib/theme/helpers/metadata.ts
This wraps `id`, `label`, and `title` props with single-quotes so the
values are always interpreted as plain strings.  It will also escape the
value appropriately.
=> avoid YAML indicators in frontmatter; fixes #80

src/lib/theme/helpers/__snapshots__/metadata.spec.ts.snap, src/lib/theme/helpers/metadata.ts
If the ID in the top matter has quotes around it, Docusaurus will include those in the filenames it generates. However, I'm not quite sure whether this solution (just removing them) is desirable; perhaps using quotes is necessary for one of the other platforms?
Fixes #25.
=> Do not use quotes for ID in the top matter

src/lib/theme/helpers/__snapshots__/metadata.spec.ts.snap, src/lib/theme/helpers/metadata.spec.ts, src/lib/theme/helpers/metadata.ts
Building on #87, this also removes the quotes around other entries in the front matter, which currently results in quotes around the titles for me in Docusaurus:
However, that did mean `escapeYAMLString` was no longer relevant, so I've removed it.  Still somewhat unsure about whether it was not added to support some other use case, though...
=> Do not enclose Front Matter strings with quotes

src/lib/theme/helpers/__snapshots__/metadata.spec.ts.snap, src/lib/theme/helpers/metadata.spec.ts, src/lib/theme/helpers/metadata.ts
As discussed in https://github.com/tgreyuk/typedoc-plugin-markdown/pull/88#issuecomment-527068036, this encloses all strings in Yaml front matter in double quotes.
=> Enclose strings in double quotes

README.md, src/index.ts, src/subthemes/docusaurus/theme.ts, src/subthemes/docusaurus2/theme.ts
* Adds to #107.
* Extends PR #108 to the docusaurus2 theme also.
* Skips finding docusaurus root when skip is enabled.
* Updates documentation to indicate it is usable for both docusaurus themes.
=> Adds skipSidebar option for docusaurus2

src/subthemes/docusaurus2/theme.ts
(I didn't really know how to properly test this, so consider this a _somewhat_ more constructive issue report.)
It might have been different in the past because Docusaurus 2 is still in Alpha, but when I just generated a new documentation website using the `classic` Docusaurus 2 preset, it did _not_ create a separate `/website` directory inside the documentation site root in which `sidebars.js` was located. Instead, `sidebars.js` was located at the root of the documentation site.
This means that the Markdown plugin for Typedoc is creating a new `/website/sidebars.js` file for me, rather than updating the existing `/sidebars.js`.
=> Fix: sidebars.js is in the website root

packages/typedoc-plugin-markdown/src/components/front-matter.component.ts, packages/typedoc-plugin-markdown/src/index.ts, packages/typedoc-plugin-markdown/src/resources/helpers/breadcrumbs.ts, packages/typedoc-plugin-markdown/src/resources/helpers/reflection-title.ts, packages/typedoc-plugin-markdown/src/resources/partials/member.hbs, packages/typedoc-plugin-markdown/src/resources/templates/reflection.member.hbs, packages/typedoc-plugin-markdown/src/theme.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/theme.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/theme.spec.ts
@jsamr this is a continuation of #154 .
Basically to get this working I have created another template. This could all be handled by custom theme implementation, however I thought this could be a useful pattern to introduce into the library. What do you think about the option `allReflectionsHaveOwnDocument` which will force a distinct output file for all reflections/members? This works quite nicely with the docusaurus sidebar. Let me know what you think.
=> Option to output all reflections into seperate files (#154)

packages/typedoc-plugin-markdown/src/resources/helpers/property-table.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/declarations.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/declarations.spec.ts, packages/typedoc-plugin-markdown/test/stubs/src/declarations.ts
There's a bug that if a property of a type definition has `_` or `|` in it, it will be escaped with a `\`. But because these are rendered within markdown `code` tags, you don't need to escape anything except ` (backtick)
Added tests to confirm that this works
=> don't escape characters in markdown `code` blocks

packages/typedoc-plugin-markdown/src/resources/helpers/type-and-parent.ts
Hi,
typedoc-plugin-markdown v3.6.0 seems like printing `Overrides: void` for all the methods which override methods of classes from external node modules. The following is a sample of the typedoc-plugin-markdown outputs of the method `Sample#once`:
```
▸ **once**(`event`: *string*, `handler`: Function, `context?`: *any*): [*Sample*](sample.md)
Overrides: void
```
Because `Sample#once` overrids `EventEmitter#once` from the external node module `eventemitter3`, `EventEmitter.once` is expected instead of `void`.
This PR is to fix this. I tried to replicate the `typeAndParent` from the `typedoc-default-themes`.
https://github.com/TypeStrong/typedoc-default-themes/blob/master/src/default/partials/typeAndParent.hbs
=> fix: Override section of methods overriding external methods

packages/typedoc-plugin-markdown/src/components/toc.ts, packages/typedoc-plugin-markdown/src/resources/helpers/toc.ts
With `hideInlinePageTOC` the heading structure is confusing. 
This PR removes the 'Table of Contents' title and assigns all groups the same heading levels.
=> Feature: Improve heading structure with disabled inline toc

packages/docusaurus-plugin-typedoc/src/front-matter.ts, packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/front-matter.spec.ts.snap, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/options.spec.ts.snap, packages/docusaurus-plugin-typedoc/test/specs/front-matter.spec.ts
Currently the sidebar for single entrypoint is 'Table of contents`. This is quite confusing as it also contains inline symbols.
This PR updates the default sidebar label to 'Exports' which also aligns with HTML theme.
This label can actually be customised with anything with the sidebar.indexLabel option.
=> Feature: (Docusaurus) Update sidebar label for 'Exports'

packages/typedoc-plugin-markdown/src/utils/front-matter.ts
Firstly, thank you for your amazing work on these plugins!
I noticed that for some of my generated files, I was getting a YAML block that looked as follows:
```
---
title: "Namespace: "QrcodeCapture""
---
```
Which led to an error when parsing the YAML. If I'm not mistaken, I think double quotes should be escaped instead of single quotes. Let me know if I'm misunderstanding something!
=> Fix string quoting bug

packages/typedoc-plugin-markdown/package.json
This addresses the discussion in #243 by removing the engines section of package.json, and relying on typedoc's engine enforcement via peer dependency.
=> Remove node 12.20 requirement from typedoc-plugin-markdown

packages/docusaurus-plugin-typedoc/src/theme.ts
This fixes the `index.md`'s `slug` value.
Without this change, docususaurus complains about broken links:
```
Info: Documentation generated at ./docs/api
✔ Client
● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
stored
Unable to build website for locale "en".
Error: Docusaurus found broken links!
Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
Exhaustive list of all broken links found:
- On source page path = /react-native-vision-camera/docs/api:
-> linking to classes/Camera (resolved as: /react-native-vision-camera/docs/classes/Camera)
-> linking to classes/CameraCaptureError …
```
=> fix: Fix `index` slug value

packages/typedoc-gitlab-wiki-theme/src/theme.ts
This was my solution for #269 
It passes lint and tests, but I'm pretty confident this is a change that could cause regressions. I'm not sure how this plugin was working for other users, but this change was required for me to produce valid docs.
=> fix(urls): Fixes relative urls for typedoc-gitlab-wiki-theme [269]

packages/vuepress-plugin-typedoc/src/plugin.ts
=> feat(vuepress-plugin-typedoc): support vuepress v2

packages/docusaurus-plugin-typedoc/README.md
Hey 👋 Thanks for the great typedoc plugins!
This change will clarify the usage of multiple plugin instances, because if the `"out"` property is not specified, the second instance will override the result of the first one.
=> docs(docusaurus-plugin-typedoc): add "out" option for multiple instances

packages/docusaurus-plugin-typedoc/package.json, packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/src/plugin.ts, packages/docusaurus-plugin-typedoc/src/types.ts, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/options.spec.ts.snap
I'm working on adding documentation to cursorless project. We want to serve documentation both from the repository as well as hosted with docusaurus + API generated by typedoc. I'm trying to create a custom read me to serve as API index with key code pointers. 
Before running docusaurus-typedoc:
```
docs/
document1.md
api/
code-pointers.md
```
After:
```
docs/
document1.md
api/ # out directory option
code-pointers.md
index.md # Just a copy of code-pointers.md
... Other typedoc documents
```
Unfortunately right now api directory gets cleaned. I have found this option https://typedoc.org/guides/options/#cleanoutputdir but looks like it's ignored by docusaurus-typedoc. This request addresses this. Only testing I have done is the unit tests which are passing.
=> Fixed ignored plugin option cleanOutputDir

packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/src/types.ts, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/options.spec.ts.snap, packages/typedoc-plugin-markdown/README.md, packages/typedoc-plugin-markdown/src/index.ts, packages/typedoc-plugin-markdown/src/render-utils.ts, packages/typedoc-plugin-markdown/src/resources/helpers/declaration-title.ts, packages/typedoc-plugin-markdown/src/resources/helpers/signature-title.ts, packages/typedoc-plugin-markdown/src/theme.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/members.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/members.spec.ts
Some markdown documentation generators do not correctly handle class member special symbols. Added an option that does not add them.
=> Added `hideMembersSymbol` option

packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/src/theme.ts, packages/docusaurus-plugin-typedoc/src/types.ts
I added the ability to prevent `docusaurus-plugin-typedoc` from generating sidebar labels.
The `sidebar_label` value in markdown files takes precedence over all other configuration options [[0]](https://docusaurus.io/docs/sidebar/items#:~:text=you%20can%2C%20however%2C%20use%20the%20sidebar_label%20markdown%20front%20matter%20within%20that%20doc%2C%20which%20has%20higher%20precedence%20over%20the%20label%20key%20in%20the%20sidebar%20item.%20). Therefore, there is no way to customize sidebar labels using this plugin. 
I added a new sidebar option `generateLabels` with a default of `true`, then if it is false, then `getSidebarLabel` for a page returns `null`, so it isn't added to the frontmatter; thus allowing a user to configure that label in their `sidebar.js` (or equivalent). 
I did try …
=> feat: Added config for generating sidebar labels

examples/docusaurus/docusaurus.config.js
Running `yarn build` errors out because of a broken docusaurus config in the examples. This removes the blog link since that directory doesn't exist to allow a successful build across the repo.
=> Remove broken blog link in docusaurus config

packages/typedoc-plugin-markdown/src/partials/member.reference.ts
This fixes the issue in the `next` branch that I mentioned here: https://github.com/tgreyuk/typedoc-plugin-markdown/issues/338#issuecomment-1221420376
=> Fix member reference link interpolation

packages/typedoc-plugin-markdown/src/partials/member.reference.ts
Second half of the fix from https://github.com/tgreyuk/typedoc-plugin-markdown/pull/341 (I forgot to quote the `href` tag)
=> Quote `href` tag

packages/typedoc-plugin-markdown/src/partials/member.signature.ts
Reference: https://github.com/tgreyuk/typedoc-plugin-markdown/issues/338#issuecomment-1242792234
Adds back in the comment block for a signature (regression from `master`)
=> [next] Add comments for return values

packages/typedoc-plugin-markdown/src/partials/member.reference.ts
Changes link from an HTML link to a markdown-style link (as `context.urlTo` keeps the `.md` extension in the returned value, it's needed otherwise it results in broken links).
=> [next] Fix link for member references 

packages/typedoc-plugin-markdown/src/resources/helpers/parameter-table.ts, packages/typedoc-plugin-markdown/src/resources/helpers/signature-title.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/declarations.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/signatures.spec.ts.snap
First off, thank you for typedoc and typedoc-plugin-markdown, they've done wonders for my documentation game :)
So I've been using [a forked version](https://github.com/xunnamius/typedoc-plugin-markdown) of the typedoc-plugin-markdown package that updates how [destructured parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) are represented in Markdown.
For example:
```typescript
export function deleteme(...[x, y]: [number, string]) {
console.log(x, y);
}
export function deleteme2(
{ a = true, b = true }: { a?: boolean; b?: boolean } = {},
state: boolean,
fate: number
) {
console.log(a, b, state, fate);
}
export function deleteme3(
{ a = true, b = true }: { a?: boolean; b?: boolean } = {},
{ c = true, d = true }: { c?: boolean; …
```
=> `typedoc-plugin-markdown`: beautify parameter table and signature title output of destructured params

packages/docusaurus-plugin-typedoc/README.md, packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/src/theme.ts, packages/docusaurus-plugin-typedoc/src/types.ts, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/options.spec.ts.snap, packages/docusaurus-plugin-typedoc/test/specs/__snapshots__/plugin.spec.ts.snap, packages/docusaurus-plugin-typedoc/test/specs/plugin.spec.ts
Surfacing this option: https://docusaurus.io/docs/sidebar/items#expanded-categories-by-default
=> feat: Add option `sidebar.collapsed`

packages/docusaurus-plugin-typedoc/src/options.ts, packages/docusaurus-plugin-typedoc/src/types.ts, packages/typedoc-plugin-markdown/README.md, packages/typedoc-plugin-markdown/src/index.ts, packages/typedoc-plugin-markdown/src/partials/member.ts, packages/typedoc-plugin-markdown/src/types.ts
Adds an option to wrap the titles of functions, interfaces, enums, etc. in a code block. This helped us be able to break up the headings (especially when you have a long module rendered all in one page) and makes it a bit easier to scan through.
=> [next] Wrap Titles in Code Block option

packages/typedoc-plugin-markdown/src/partials/type.some.ts, packages/typedoc-plugin-markdown/src/partials/type.unknown.ts
Previously some back-ticked content was escaping characters. When this is done in code blocks it was causing unwanted escaping (see the `x86\_64` entry when it should just be `x86_64`: 
Now this removes any redundant escaping:
In the future if there are things that should be escaped WITHIN backtick blocks, I'd assume that should be handled inside the `backTicks` function and not by wrapping that in `escapeChars`
=> [next] Fix escaped chars in backticks

packages/typedoc-plugin-markdown/src/partials/member.reference.ts
Fix a typo I introduced in bad437101b7bc00280d780e13273859b05eab8e3
=> [next] Fix typo in member reference file

packages/typedoc-plugin-markdown/src/partials/reflection.ts
Removes usage of `horizontalRule` throughout code but retains the helper function for future use per https://github.com/tgreyuk/typedoc-plugin-markdown/discussions/372#discussioncomment-4403613
=> [next] Remove horizontalRule usage for reflections

packages/typedoc-plugin-markdown/src/partials/member.declaration.title.ts, packages/typedoc-plugin-markdown/src/partials/member.signature.title.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/declarations.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/generics.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/signatures.spec.ts.snap
This changes the design of member signature titles as well as member declaration titles from this:
to this:
=> [next] Change Signature Styling

packages/docusaurus-plugin-typedoc/src/render.ts
This was driving me crazy. Turns out `docusaurus-plugin-typedoc` doesn't read `typedocOptions` from `package.json`, even though the `typedoc` command line tool does.
PS. Maybe add these lines to `vuepress-plugin-typedoc` as well?
=> Enable the package.json loader, so options may be read from typedocOptions

packages/typedoc-gitlab-wiki-theme/src/theme.ts
This fixes an issue I encountered when using the gitlab-wiki-theme.
The links that are generated have a `-` that replaces spaces in the referenced reflections, however the filenames of the relevant reflections still have spaces. This leads to all links with spaces being broken in the gitlab wiki.
This is on GitLab Enterprise Edition [v16.0.4-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.0.4-ee)
Using the following dependency tree:
```sh
> npm ls typedoc
my-package ~/my-package
├─┬ typedoc-gitlab-wiki-theme@1.1.0
│ └── typedoc@0.25.1 deduped
├─┬ typedoc-plugin-markdown@3.16.0
│ └── typedoc@0.25.1 deduped
└── typedoc@0.25.1
```
=> fix: spaces in filenames results in broken links

packages/docusaurus-plugin-typedoc/src/plugin.ts
The generate-typedoc CLI command would run typedoc on every plugin instance defined on the site, not just for the current one. This would cause generation to fail with errors "Tried to set an option that was not declared", since the config for other plugins would not pass the validation for this plugin.
This fix checks that the plugin name matches the current one before running generateTypedoc on it.
=> fix: CLI command skips unrelated plugins

packages/typedoc-plugin-markdown/src/theme/urls-context.ts
Closes #471
* * *
I have no idea if this is correct, and I didn't change any tests to support it; please let me know if a) this is correct, and b) if so, where I can add a test?
thanks!
=> fix: generate packages.md even if groups used

packages/typedoc-plugin-markdown/src/theme/resources/partials/breadcrumbs.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/comment.parts.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/list.parameters.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/member.declaration.identifier.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/member.declaration.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/member.type-declaration.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/table.parameters.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/type-argumentsts.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/type.declaration.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/type.reference.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/type.reflection.ts, packages/typedoc-plugin-markdown/src/theme/resources/partials/type.some.ts
This PR fixes the TS typing for `MarkdownThemeRenderContext.partials`. 
**Before**
```ts
// dist/theme/theme-render-context.d.ts
/**
* The theme's global partials context.
*/
partials: any;
```
**After**
```ts
// dist/theme/theme-render-context.d.ts
/**
* The theme's global partials context.
*/
partials: {
breadcrumbs: (page: MarkdownPageEvent<import("typedoc").DeclarationReflection | import("typedoc").ProjectReflection>) => string;
commentParts: (parts: import("typedoc").CommentDisplayPart[]) => string;
...
```
=> fix: provide correct types for partials

packages/docusaurus-plugin-typedoc/src/plugin.ts
Fixes https://github.com/tgreyuk/typedoc-plugin-markdown/issues/583
=> fix: exit code 1 when typedoc is failing

packages/typedoc-plugin-remark/src/remark.cjs
Hi,
I have been using the typedoc-plugin-markdown plugin for some time and stubled across a problem where I needed to rewrite relative links from `myMarkDownFile.md` to `./myMarkDownFile.md`. In my attempt to find a solution to do that I came across the next branch of your repository.
While trying it out, I encountered this error:
```
Error: `processSync` finished async. Use `process` instead
at assertDone (file:///Users/<retracted>javascript/core-api/node_modules/unified/lib/index.js:1273:11)
at Function.processSync (file:///Users/<retracted>/javascript/core-api/node_modules/unified/lib/index.js:820:5)
at parseContents (/Users/<retracted>/javascript/core-api/node_modules/typedoc-plugin-remark/dist/remark.cjs:35:15)
at async /Users/<retracted>/javascript/core-api/node_modules/typedoc-plugi …
```
=> Use remark.process instead of remark.processSync

packages/typedoc-plugin-markdown/src/theme/context/partials/member.typeDeclarationTable.ts
when parameters are rendered in a table and the type is optional, then `?` is missing after the type name
=> fix: add '?' for optional params in tables

packages/typedoc-plugin-markdown/src/theme/context/helpers/get-comment-parts.ts, packages/typedoc-plugin-markdown/test/fixtures/src/comments/index.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/comments.spec.ts.snap
I noticed that when referring to specific section of the project documents, anchors were missing.
=> fix(core): preserve anchors in project document links

GETTING_STARTED.md, devguide/documents/Getting-Started.md, packages/typedoc-plugin-markdown/src/theme/context/partials/member.parametersTable.ts, packages/typedoc-plugin-markdown/src/theme/context/partials/member.signatureParameters.ts, packages/typedoc-plugin-markdown/src/theme/context/partials/member.typeDeclarationTable.ts, packages/typedoc-plugin-markdown/src/theme/context/partials/type.reflection.function.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/objects-and-params.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/reflection.function.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/reflection.interface.spec.ts.snap
Hello!
As discussed in https://github.com/typedoc2md/typedoc-plugin-markdown/discussions/796 I'm putting up this PR to move occurrences of the `?` / `isOptional` flag inside any `backTicks` call. Previously it was inconsistent and sometimes inside, sometimes outside.
=> fix(core): Move `isOptional` flag inside `backTicks`

package-lock.json, packages/typedoc-plugin-markdown/src/theme/context/partials/member.signatureParameters.ts, packages/typedoc-plugin-markdown/src/theme/context/partials/type.reflection.declaration.ts, packages/typedoc-plugin-markdown/src/theme/context/resources.ts, packages/typedoc-plugin-markdown/test/specs/__snapshots__/objects-and-params.spec.ts.snap, packages/typedoc-plugin-markdown/test/specs/__snapshots__/reflection.function.spec.ts.snap
- A naive fix for formatting issue when optional or getter/setter properties used
- All example below was generated with `useCodeBlock` on
current the plugin formats optional type in type declaration like so:
code:
```typescript
export type TypeHasOptional = {
foo?: string;
};
```
before the change it generates:
```ts
type TypeHasOptional = {
foo: string;
};
```
after the change it generates:
```ts
type TypeHasOptional = {
foo?: string;
};
```
code: 
```typescript
export type TypeHasGetter = {
get foo(): string | undefined;
};
```
before the change it generates:
```ts
type TypeHasGetter = {
get foo
foo: undefined | string;
};
```
afterward:
```ts
type TypeHasGetter = {
get foo(): undefined | string;
};
```
code:
```typescript
export type TypeHasSetter = {
set foo(value: string | …
```
=> fix(core): format of optional type and getter/setter

packages/typedoc-plugin-markdown/src/theme/context/helpers/get-keyword.ts, packages/typedoc-plugin-markdown/src/theme/context/resources.ts
`getKeyword` doesn't not handle all `ReflectionKind`, thus it should return a string _or an undefined_.
=> fix(core): correct return type of `helpers.getKeyword`
